//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesafioPitang.Utils.Messages {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class BusinessMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BusinessMessages() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DesafioPitang.Utils.Messages.BusinessMessages", typeof(BusinessMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O registro não foi encontrado..
        /// </summary>
        public static string ElementNotFound {
            get {
                return ResourceManager.GetString("ElementNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O nome do paciente deve ser inserido..
        /// </summary>
        public static string EmptySchedulePatientName {
            get {
                return ResourceManager.GetString("EmptySchedulePatientName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O Email é um campo obrigatório..
        /// </summary>
        public static string EmptyUserEmail {
            get {
                return ResourceManager.GetString("EmptyUserEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O Nome de usuário deve ser inserido..
        /// </summary>
        public static string EmptyUserName {
            get {
                return ResourceManager.GetString("EmptyUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A Senha é um campo obrigatório..
        /// </summary>
        public static string EmptyUserPassword {
            get {
                return ResourceManager.GetString("EmptyUserPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não existem mais vagas disponíveis para este dia..
        /// </summary>
        public static string FullScheduleDate {
            get {
                return ResourceManager.GetString("FullScheduleDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não existem mais vagas disponíveis para este horário..
        /// </summary>
        public static string FullScheduleTime {
            get {
                return ResourceManager.GetString("FullScheduleTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O status &quot;{0}&quot; é inválido..
        /// </summary>
        public static string InvalidAppointmentStatus {
            get {
                return ResourceManager.GetString("InvalidAppointmentStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A data inicial deve ser menor ou igual a data final..
        /// </summary>
        public static string InvalidDateRange {
            get {
                return ResourceManager.GetString("InvalidDateRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Email e(ou) senha inválidos..
        /// </summary>
        public static string InvalidLoginFields {
            get {
                return ResourceManager.GetString("InvalidLoginFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Agendamentos só podem ser feitos a partir da data atual..
        /// </summary>
        public static string InvalidScheduleAppointmentDate {
            get {
                return ResourceManager.GetString("InvalidScheduleAppointmentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A data de nascimento deve ser anterior ou igual a o dia de hoje..
        /// </summary>
        public static string InvalidScheduleBirthdate {
            get {
                return ResourceManager.GetString("InvalidScheduleBirthdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O agendamento deve ocorrer entre 05:00 e 20:00..
        /// </summary>
        public static string InvalidScheduleTime {
            get {
                return ResourceManager.GetString("InvalidScheduleTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O intervalo de tempo entre um agendamento e outro é de 1 hora..
        /// </summary>
        public static string InvalidScheduleTimeRange {
            get {
                return ResourceManager.GetString("InvalidScheduleTimeRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O campo Email está inválido..
        /// </summary>
        public static string InvalidUserEmail {
            get {
                return ResourceManager.GetString("InvalidUserEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O perfil de usuário &quot;{0}&quot; é inválido..
        /// </summary>
        public static string InvalidUserProfile {
            get {
                return ResourceManager.GetString("InvalidUserProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O nome do paciente não pode conter números..
        /// </summary>
        public static string PatientNameWithNumbers {
            get {
                return ResourceManager.GetString("PatientNameWithNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A senha inserida é muito curta (mínimo 6 caracteres)..
        /// </summary>
        public static string ShortUserPassword {
            get {
                return ResourceManager.GetString("ShortUserPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O nome do usuario não pode conter números..
        /// </summary>
        public static string UserNameWithNumbers {
            get {
                return ResourceManager.GetString("UserNameWithNumbers", resourceCulture);
            }
        }
    }
}
